In [1]:
#LEARN NUMPY

In [2]:
import numpy as np

In [3]:
#Few Important Functions 

In [4]:
a = np.array([1,2,3,4])

In [5]:
print(a)

[1 2 3 4]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a.shape

(4,)

In [8]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [11]:
b.shape


(2, 5)

In [12]:
b.T


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [13]:
np.dot(b,b.T)

array([[ 55, 130],
       [130, 330]])

In [19]:
matrix = np.random.randint(60,400,(10,10))#first two places are of range and last place is of number 

In [20]:
print(matrix)

[[397 392 229 313 152 299 272 288 372 353]
 [177 193 143  73 256 378  71  97 107 349]
 [276 194 382  82 279 177 279  97 156 186]
 [145 269 326 335 147 315 279  71 282 322]
 [138 161 367  73 338  89 227 292 357 290]
 [363 267 384 371 339 336 211 229 217 247]
 [345 186 339 248 154 139 179 351 267 149]
 [388  94 132 348 246 167 131 201 303 298]
 [ 88 212 392 274 306 118 328  80 225 225]
 [104 303 303  69  77 377 326 133 207 312]]


In [21]:
np.min(matrix)

69

In [25]:
a = np.array([0,1,2,-8,6,
             8,10])

In [26]:
np.argmin(a) # returns index of min element in the array

3

In [34]:
b=np.unique(a,return_counts = True) #return_counts retrun the frequency of number occuring in the array 

In [35]:
#Program to ind out the Number with the highest frequency in the array

In [36]:
idx = np.argmax(b[1]) #index with highest freq
element = b[0][idx]
print(element)

-8


In [39]:
#slicing of Arrays (1D,2D,3D)

In [42]:
matrix[2:4,1:4]

array([[194, 382,  82],
       [269, 326, 335]])

In [43]:
matrix[0][0]

397